# Generated by Django 3.1 on 2020-09-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employeeprofile_workstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('alternate_mobile_no', models.IntegerField(max_length=10)),
                ('aadhar_no', models.IntegerField()),
                ('pan_no', models.TextField()),
                ('address', models.TextField()),
                ('purpose_of_enrol', models.CharField(choices=[(11, 'Tractors'), (12, 'Implements'), (13, 'Both')], max_length=20)),
                ('tractor_exists', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Do you have a tractor?')),
                ('tractor_name_model', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('agriland_exists', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Do you have agriculture land?')),
                ('land_acres', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loans', models.TextField()),
                ('new_tractor', models.CharField(choices=[(11, 'Immediate'), (12, 'Within a week'), (13, 'Within a month'), (14, 'Other')], max_length=20)),
                ('t_c', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you agree?')),
            ],
        ),
    ]
