# Generated by Django 3.1 on 2020-09-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200921_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='Empid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='completed_sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='target',
            field=models.IntegerField(),
        ),
    ]
