# Generated by Django 3.1 on 2020-09-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200921_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar_no',
            field=models.CharField(max_length=12, verbose_name='Aadhar Card Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='land_acres',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Land in acres'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loans',
            field=models.TextField(verbose_name='Loan Details'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_no',
            field=models.CharField(max_length=10, verbose_name='PAN Card Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='purpose_of_enrol',
            field=models.CharField(choices=[(11, 'Tractors'), (12, 'Implements'), (13, 'Both')], max_length=20, verbose_name='Purpose of Enrollment'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tractor_name_model',
            field=models.CharField(max_length=300, verbose_name='Tractor Name & Model'),
        ),
    ]
