# Generated by Django 3.1 on 2020-09-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200921_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='alternate_mobile_no',
            field=models.CharField(max_length=10, verbose_name='Alternate Mobile No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='father_name',
            field=models.CharField(max_length=100, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=models.CharField(max_length=10, verbose_name='Mobile No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='new_tractor',
            field=models.CharField(choices=[(11, 'Immediate'), (12, 'Within a week'), (13, 'Within a month'), (14, 'Other')], max_length=20, verbose_name='Planning for a new tractor in?'),
        ),
    ]
