# Generated by Django 3.1 on 2020-09-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_employeeprofile_empimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='enrol_id',
            field=models.CharField(max_length=6, null=True, verbose_name='Customer Id'),
        ),
    ]
