# Generated by Django 3.1 on 2020-09-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200922_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agriland_exists',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Do you have agriculture land?'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(help_text='Please mention the date of birth in YY/MM/DD format', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='t_c',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Do you agree?'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tractor_exists',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Do you have a tractor?'),
        ),
    ]
