# Generated by Django 3.1 on 2020-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200922_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhar_no',
            field=models.CharField(help_text='Please enter the correct Aadhar number', max_length=12, verbose_name='Aadhar Card Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='enrol_id',
            field=models.CharField(max_length=9, null=True, verbose_name='Customer Id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_no',
            field=models.CharField(help_text='Please enter the correct PAN number', max_length=10, verbose_name='PAN Card Number'),
        ),
    ]
