# Generated by Django 3.1 on 2020-09-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20200922_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonENESaleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=9, verbose_name='Sale ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(help_text='Please mention the date of birth in YY/MM/DD format', verbose_name='Date of Birth')),
                ('father_name', models.CharField(max_length=100, verbose_name='Father Name')),
                ('mobile_no', models.CharField(max_length=10, verbose_name='Mobile No')),
                ('alternate_mobile_no', models.CharField(max_length=10, verbose_name='Alternate Mobile No')),
                ('aadhar_no', models.CharField(help_text='Please enter the correct Aadhar number', max_length=12, verbose_name='Aadhar Card Number')),
                ('pan_no', models.CharField(help_text='Please enter the correct PAN number', max_length=10, verbose_name='PAN Card Number')),
                ('present_address', models.TextField(null=True, verbose_name='Present Address')),
                ('permanent_address', models.TextField(null=True, verbose_name='Permanent Address')),
                ('product_category', models.CharField(choices=[('Tractor', 'Tractor'), ('Implement', 'Implement')], max_length=50, verbose_name='Product Category')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('mfg_date', models.DateField(help_text='Please mention the manufactured date in YY/MM/DD format', verbose_name='Product Manufactured Date')),
                ('sale_date', models.DateField(help_text='Please mention the date of sale in YY/MM/DD format', verbose_name='Date of Sale')),
                ('payment_type', models.CharField(choices=[('Finance', 'Finance'), ('Cash', 'Cash')], max_length=50, verbose_name='Mode of Payment')),
                ('financer', models.CharField(max_length=100, verbose_name='Financer Name')),
                ('finance_hypothecation', models.CharField(max_length=100, verbose_name='Finance Hypothecation')),
                ('sale_delivery_date', models.DateField(help_text='Please mention the sale delivery date in YY/MM/DD format', verbose_name='Sale Delivery Date')),
                ('temporary_registration_number', models.CharField(max_length=50, verbose_name='Temporary Registration Number')),
                ('rta_authority', models.CharField(max_length=100, verbose_name='RTA Authority')),
                ('docs_handovered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Documents handovered to Customer?')),
                ('employee_id', models.CharField(max_length=10, verbose_name='Employee ID')),
                ('workstation_code', models.CharField(max_length=50, verbose_name='Workstation Code')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='permanent_address',
            field=models.TextField(null=True, verbose_name='Permanent Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='present_address',
            field=models.TextField(null=True, verbose_name='Present Address'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='Empid',
            field=models.CharField(max_length=10, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='empimage',
            field=models.ImageField(blank=True, upload_to='Images', verbose_name='Employee Profile Image'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='workstation',
            field=models.CharField(default='Hyderabad', max_length=50, verbose_name='Workstation Code'),
        ),
    ]
