# Generated by Django 3.1 on 2020-09-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200923_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonenesaleentry',
            options={'verbose_name': 'Non Enrolled Customers Sale Entry', 'verbose_name_plural': 'Non Enrolled Customers Sale Entries'},
        ),
    ]
