# Generated by Django 3.1 on 2020-09-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20200923_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(help_text='Please mention the date of birth in YYYY/MM/DD format', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='nonenesaleentry',
            name='date_of_birth',
            field=models.DateField(help_text='Please mention the date of birth in YYYY/MM/DD format', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='nonenesaleentry',
            name='mfg_date',
            field=models.DateField(help_text='Please mention the manufactured date in YYYY/MM/DD format', verbose_name='Product Manufactured Date'),
        ),
        migrations.AlterField(
            model_name='nonenesaleentry',
            name='sale_date',
            field=models.DateField(help_text='Please mention the date of sale in YYYY/MM/DD format', verbose_name='Date of Sale'),
        ),
        migrations.AlterField(
            model_name='nonenesaleentry',
            name='sale_delivery_date',
            field=models.DateField(help_text='Please mention the sale delivery date in YYYY/MM/DD format', verbose_name='Sale Delivery Date'),
        ),
    ]
