# Generated by Django 3.1 on 2020-09-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20200923_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enesaleentry',
            options={'verbose_name': 'Enrolled Customers Sale Entry', 'verbose_name_plural': 'Enrolled Customers Sale Entries'},
        ),
    ]
