# Generated by Django 3.1 on 2020-09-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20200923_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='enesaleentry',
            name='sale_id',
            field=models.CharField(blank=True, max_length=9, verbose_name='Sale ID'),
        ),
    ]
