# Generated by Django 3.1 on 2020-09-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_enesaleentry_sale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enesaleentry',
            name='enrolled_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.customer', verbose_name='Enrollment ID'),
        ),
    ]
