# Generated by Django 3.1 on 2020-09-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20200924_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enesaleentry',
            name='enrolled_id',
            field=models.CharField(blank=True, max_length=9, verbose_name='Enrollment ID'),
        ),
    ]
