# Generated by Django 3.1 on 2020-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_usedtractorverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedtractorverification',
            options={'verbose_name': 'Used Tractor Verification Entries', 'verbose_name_plural': 'Used Tractor Verification Entries'},
        ),
        migrations.AddField(
            model_name='usedtractorverification',
            name='verification_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='Verification Id'),
        ),
    ]
