# Generated by Django 3.1 on 2020-10-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20201005_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedtractorverification',
            options={'verbose_name': 'Used Tractor Verification Entry', 'verbose_name_plural': 'Used Tractor Verification Entries'},
        ),
    ]
