# Generated by Django 3.1 on 2020-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20201005_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Enrolled Customer', 'verbose_name_plural': 'Enrolled Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='usedtractorverification',
            name='looking_for',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Exchange', 'Exchange')], max_length=20, verbose_name='Sale or Exchange?'),
        ),
        migrations.AlterField(
            model_name='usedtractorverification',
            name='verification_id',
            field=models.CharField(blank=True, max_length=9, verbose_name='Verification Id'),
        ),
    ]
