# Generated by Django 3.1 on 2020-10-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20201008_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedtractorverification',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Employee ID'),
        ),
    ]
