# Generated by Django 3.1 on 2020-10-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20201011_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedtractorverification',
            name='used_trac_price',
            field=models.CharField(max_length=20, null=True, verbose_name='Used Tractor Price by Decider'),
        ),
    ]
